name: Automatic Commit
on:
  schedule:
    - cron: '40 6 * * *'
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "haa-meem"
          git config user.email "haameemalhamra@gmail.com"
          git add -p sort.js -e "7-11"
          git commit -m "Automatic commit of sort.js"
          git push